# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('posts', models.TextField(blank=True, null=True)),
                ('page_info', models.TextField(blank=True, null=True)),
                ('most_liked_post', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
